;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-previous-line
        indent-for-tab-command
        isearch-forward-regexp
        ))

(setq mc/cmds-to-run-once
      '(
        evil-next-line
        evil-scroll-down
        ))
